AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Meeting Processor: Step Functions workflow to transcribe videos.

Parameters:
  S3BucketName:
    Type: String
    Description: "The name of the S3 bucket for storing all meeting files."
    Default: "meeting-minutes-processor-files-us-west-2"

Resources:
  # S3 Bucket for all application files
  MeetingFilesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      LifecycleConfiguration:
        Rules:
          - Id: AutoDeleteProcessingFiles
            Prefix: "transcripts/"
            Status: Enabled
            ExpirationInDays: 7
          - Id: AutoDeleteConvertedFiles
            Prefix: "converted/"
            Status: Enabled
            ExpirationInDays: 7
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  # Explicit Bucket Policy to allow S3 to publish events and Transcribe to access the bucket
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MeetingFilesBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowS3ToPublishEventsToEventBridge"
            Effect: "Allow"
            Principal:
              Service: "s3.amazonaws.com"
            Action: "s3:PutBucketNotification"
            Resource: !GetAtt MeetingFilesBucket.Arn
            Condition:
              StringEquals:
                "s3:ResourceAccount": !Ref AWS::AccountId
          - Sid: "AllowTranscribeService"
            Effect: "Allow"
            Principal:
              Service: "transcribe.amazonaws.com"
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
            Resource: !Sub "arn:aws:s3:::${MeetingFilesBucket}/*"
          - Sid: "AllowMediaConvertService"
            Effect: "Allow"
            Principal:
              Service: "mediaconvert.amazonaws.com"
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
            Resource: !Sub "arn:aws:s3:::${MeetingFilesBucket}/*"

  # SNS Topic for email notifications
  EmailNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "meeting-processor-notifications-${AWS::StackName}"
      DisplayName: "Meeting Processor Email Notifications"

  # Lambda Function to send email notifications
  EmailSenderLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/email_sender/
      Handler: handler.lambda_handler
      Runtime: python3.12
      Timeout: 60
      MemorySize: 256
      Architectures: [x86_64]
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3ReadPolicy:
            BucketName: "k12-temp-testing-static-files"
        - S3ReadPolicy:
            BucketName: !Ref MeetingFilesBucket
        - Statement:
            - Effect: Allow
              Action:
                - "sns:Publish"
                - "sns:Subscribe"
                - "sns:ListSubscriptionsByTopic"
              Resource: !Ref EmailNotificationTopic
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref EmailNotificationTopic

  # Lambda Function to process the final transcript
  ProcessTranscriptLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/process_transcript/
      Handler: handler.handler
      Runtime: python3.9
      Timeout: 900 # Maximum Lambda timeout for chunked processing and Bedrock calls (15 minutes)
      MemorySize: 2048 # Increased for processing multiple transcripts and merging
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource: !Sub "arn:aws:s3:::${MeetingFilesBucket}/*"
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource: !GetAtt MeetingFilesBucket.Arn
            # Access to external bucket for prompt and agenda
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: "arn:aws:s3:::k12-temp-testing-static-files/*"
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource: "arn:aws:s3:::k12-temp-testing-static-files"
            # 1. Allow the cross-region inference profile itself
            - Sid: AllowBedrockProfile
              Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource:
                # use !Sub so ${AWS::AccountId} resolves before IAM parses JSON
                - !Sub arn:aws:bedrock:us-west-2:${AWS::AccountId}:inference-profile/us.anthropic.claude-3-7-sonnet-20250219-v1:0
            # 2. Allow every foundation-model ARN the profile may route to
            - Sid: AllowBedrockFoundationModels
              Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource:
                - arn:aws:bedrock:us-east-1::foundation-model/anthropic.claude-3-7-sonnet-20250219-v1:0
                - arn:aws:bedrock:us-east-2::foundation-model/anthropic.claude-3-7-sonnet-20250219-v1:0
                - arn:aws:bedrock:us-west-2::foundation-model/anthropic.claude-3-7-sonnet-20250219-v1:0

      Environment:
        Variables:
          S3_BUCKET: !Ref MeetingFilesBucket

  # Lambda Function to verify S3 file exists
  VerifyS3FileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/verify_s3_file/
      Handler: handler.lambda_handler
      Runtime: python3.12
      Timeout: 120
      MemorySize: 256
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3ReadPolicy:
            BucketName: !Ref MeetingFilesBucket
        - Statement:
            - Effect: Allow
              Action:
                - mediaconvert:GetJob
              Resource: "*"

  # Lambda Function to trigger MediaConvert jobs (uses existing pymediainfo layer by ARN)
  MediaConvertTriggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/mediaconvert_trigger/
      Handler: handler.lambda_handler
      Runtime: python3.12
      Timeout: 330
      MemorySize: 2048
      Architectures: [x86_64]
      Layers:
        - arn:aws:lambda:us-west-2:412072465402:layer:pymediainfo:3
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3ReadPolicy:
            BucketName: !Ref MeetingFilesBucket
        - S3CrudPolicy:
            BucketName: !Ref MeetingFilesBucket
        - Statement:
            - Effect: Allow
              Action:
                - mediaconvert:CreateJob
                - mediaconvert:GetJob
                - mediaconvert:DescribeEndpoints
              Resource: "*"
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource: !Sub "arn:aws:iam::${AWS::AccountId}:role/MediaConvertServiceRole"
      Environment:
        Variables:
          LD_LIBRARY_PATH: "/opt/python/"

  # Step Functions State Machine to orchestrate the workflow
  TranscriptionStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: STANDARD
      DefinitionUri: statemachine/transcribe.asl.json
      DefinitionSubstitutions:
        ProcessTranscriptLambdaArn: !GetAtt ProcessTranscriptLambda.Arn
        MediaConvertLambdaArn: !GetAtt MediaConvertTriggerFunction.Arn
        VerifyS3FileLambdaArn: !GetAtt VerifyS3FileFunction.Arn
        EmailSenderLambdaArn: !GetAtt EmailSenderLambda.Arn
        OutputBucketName: !Ref S3BucketName
      Events:
        S3UploadTrigger:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - aws.s3
              detail-type:
                - "Object Created"
              detail:
                bucket:
                  name:
                    - !Ref S3BucketName
                object:
                  key:
                    - prefix: "uploads/"
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ProcessTranscriptLambda
        - LambdaInvokePolicy:
            FunctionName: !Ref VerifyS3FileFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref EmailSenderLambda
        - Statement:
            - Effect: Allow
              Action:
                - "lambda:InvokeFunction"
              Resource: !GetAtt MediaConvertTriggerFunction.Arn
            - Effect: Allow
              Action:
                - "transcribe:StartTranscriptionJob"
                - "transcribe:GetTranscriptionJob"
              Resource: "*"
            - Effect: Allow
              Action:
                - "mediaconvert:GetJob"
              Resource: "*"
            - Effect: Allow
              Action:
                - "s3:GetObject"
              Resource:
                - !Sub "arn:aws:s3:::${S3BucketName}/uploads/*"
                - !Sub "arn:aws:s3:::${S3BucketName}/audio/*"
            - Effect: Allow
              Action:
                - "s3:PutObject"
              Resource:
                - !Sub "arn:aws:s3:::${S3BucketName}/transcripts/*"
                - !Sub "arn:aws:s3:::${S3BucketName}/converted/*"

Outputs:
  S3Bucket:
    Description: "Name of the S3 bucket for meeting files"
    Value: !Ref MeetingFilesBucket
  StateMachineArn:
    Description: "ARN of the Step Functions State Machine"
    Value: !Ref TranscriptionStateMachine
  MediaConvertLambdaArn:
    Description: "ARN of the MediaConvert trigger Lambda function managed by this stack"
    Value: !GetAtt MediaConvertTriggerFunction.Arn
  VerifyS3FileLambdaArn:
    Description: "ARN of the S3 file verification Lambda function"
    Value: !GetAtt VerifyS3FileFunction.Arn
  EmailNotificationTopicArn:
    Description: "SNS Topic ARN for email notifications"
    Value: !Ref EmailNotificationTopic
  EmailSenderLambdaArn:
    Description: "Email Sender Lambda function ARN"
    Value: !GetAtt EmailSenderLambda.Arn
